name: Run Jupyter Notebook

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # 수동 실행 버튼

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert pandas requests markdown

      - name: Run notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute "AI교육_실습3(25_12_23).ipynb" \
            --output executed.ipynb

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: executed.ipynb
